[package]
name = "xenopeltis"
version = "0.1.0"
edition = "2021"
authors = ["Daniel He <he.daniel@protonmail.com", "Patrick Elsen <pelsen@xfbs.net>"]
description = "Multiplayer terminal snake game"
repository = "https://github.com/0xdh/xenopeltis"
workspace = ".."

[dependencies]
